# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: backend
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjU2NjczNzE5OTcwYTI2ZGMyYTMzYWExZTllNmQyMWUwODg5OGI2OWE1NzUxNTZiNzQ1N2RhYWY5MTFkZWE4M2YwM2IzM2NmMTJmYzhkODk4ODBkMmJiYTU3MDU0NjJhNmI4Yjk4ZTA4ZDYwNzM1MzE1ZTE4MmRiOWQzY2EyMWU=
