# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  # Do not override dev datasource credentials.
  # In prod/CI you should set SPRING_DATASOURCE_USERNAME / SPRING_DATASOURCE_PASSWORD.
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YThmZTY3ODQ4Zjk1Y2QwYTZmMzZjM2Q1YmU3NGNiYTQxMmE1YWU0MjgxNjgyMGEyN2QyY2ViODRlYzFmZjg5M2Y5ZTI4MjA4YjM3ZWYwMTE2Mjk5NzI1YzBiZTFlOGQ3MDM5OTcyNzVmNTY0NDkyMzY5OGYwN2YzMGEyOTg1OGU=
