package com.finance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BusinessAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessAllPropertiesEquals(Business expected, Business actual) {
        assertBusinessAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessAllUpdatablePropertiesEquals(Business expected, Business actual) {
        assertBusinessUpdatableFieldsEquals(expected, actual);
        assertBusinessUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessAutoGeneratedPropertiesEquals(Business expected, Business actual) {
        assertThat(actual)
            .as("Verify Business auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUpdatableFieldsEquals(Business expected, Business actual) {
        assertThat(actual)
            .as("Verify Business relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getOwnerName()).as("check ownerName").isEqualTo(expected.getOwnerName()))
            .satisfies(a -> assertThat(a.getMobile()).as("check mobile").isEqualTo(expected.getMobile()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getLogoUrl()).as("check logoUrl").isEqualTo(expected.getLogoUrl()))
            .satisfies(a -> assertThat(a.getGstNumber()).as("check gstNumber").isEqualTo(expected.getGstNumber()))
            .satisfies(a -> assertThat(a.getPanNumber()).as("check panNumber").isEqualTo(expected.getPanNumber()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getState()).as("check state").isEqualTo(expected.getState()))
            .satisfies(a -> assertThat(a.getBillingLine1()).as("check billingLine1").isEqualTo(expected.getBillingLine1()))
            .satisfies(a -> assertThat(a.getBillingLine2()).as("check billingLine2").isEqualTo(expected.getBillingLine2()))
            .satisfies(a -> assertThat(a.getBillingCity()).as("check billingCity").isEqualTo(expected.getBillingCity()))
            .satisfies(a -> assertThat(a.getBillingState()).as("check billingState").isEqualTo(expected.getBillingState()))
            .satisfies(a -> assertThat(a.getBillingPincode()).as("check billingPincode").isEqualTo(expected.getBillingPincode()))
            .satisfies(a -> assertThat(a.getShippingLine1()).as("check shippingLine1").isEqualTo(expected.getShippingLine1()))
            .satisfies(a -> assertThat(a.getShippingLine2()).as("check shippingLine2").isEqualTo(expected.getShippingLine2()))
            .satisfies(a -> assertThat(a.getShippingCity()).as("check shippingCity").isEqualTo(expected.getShippingCity()))
            .satisfies(a -> assertThat(a.getShippingState()).as("check shippingState").isEqualTo(expected.getShippingState()))
            .satisfies(a -> assertThat(a.getShippingPincode()).as("check shippingPincode").isEqualTo(expected.getShippingPincode()))
            .satisfies(a ->
                assertThat(a.getShippingSameAsBilling()).as("check shippingSameAsBilling").isEqualTo(expected.getShippingSameAsBilling())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getFyStartMonth()).as("check fyStartMonth").isEqualTo(expected.getFyStartMonth()))
            .satisfies(a -> assertThat(a.getHasData()).as("check hasData").isEqualTo(expected.getHasData()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUpdatableRelationshipsEquals(Business expected, Business actual) {
        // empty method
    }
}
