package com.finance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExpenseCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryAllPropertiesEquals(ExpenseCategory expected, ExpenseCategory actual) {
        assertExpenseCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertExpenseCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryAllUpdatablePropertiesEquals(ExpenseCategory expected, ExpenseCategory actual) {
        assertExpenseCategoryUpdatableFieldsEquals(expected, actual);
        assertExpenseCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryAutoGeneratedPropertiesEquals(ExpenseCategory expected, ExpenseCategory actual) {
        assertThat(actual)
            .as("Verify ExpenseCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryUpdatableFieldsEquals(ExpenseCategory expected, ExpenseCategory actual) {
        assertThat(actual)
            .as("Verify ExpenseCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryUpdatableRelationshipsEquals(ExpenseCategory expected, ExpenseCategory actual) {
        assertThat(actual)
            .as("Verify ExpenseCategory relationships")
            .satisfies(a -> assertThat(a.getBusiness()).as("check business").isEqualTo(expected.getBusiness()));
    }
}
