package com.finance.app.domain;

import static com.finance.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PartyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartyAllPropertiesEquals(Party expected, Party actual) {
        assertPartyAutoGeneratedPropertiesEquals(expected, actual);
        assertPartyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartyAllUpdatablePropertiesEquals(Party expected, Party actual) {
        assertPartyUpdatableFieldsEquals(expected, actual);
        assertPartyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartyAutoGeneratedPropertiesEquals(Party expected, Party actual) {
        assertThat(actual)
            .as("Verify Party auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartyUpdatableFieldsEquals(Party expected, Party actual) {
        assertThat(actual)
            .as("Verify Party relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getMobile()).as("check mobile").isEqualTo(expected.getMobile()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getAddressLine1()).as("check addressLine1").isEqualTo(expected.getAddressLine1()))
            .satisfies(a -> assertThat(a.getAddressCity()).as("check addressCity").isEqualTo(expected.getAddressCity()))
            .satisfies(a -> assertThat(a.getAddressState()).as("check addressState").isEqualTo(expected.getAddressState()))
            .satisfies(a -> assertThat(a.getAddressPincode()).as("check addressPincode").isEqualTo(expected.getAddressPincode()))
            .satisfies(a -> assertThat(a.getGstNumber()).as("check gstNumber").isEqualTo(expected.getGstNumber()))
            .satisfies(a -> assertThat(a.getPanNumber()).as("check panNumber").isEqualTo(expected.getPanNumber()))
            .satisfies(a ->
                assertThat(a.getCreditLimit())
                    .as("check creditLimit")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCreditLimit())
            )
            .satisfies(a -> assertThat(a.getPaymentTermsDays()).as("check paymentTermsDays").isEqualTo(expected.getPaymentTermsDays()))
            .satisfies(a ->
                assertThat(a.getOpeningBalance())
                    .as("check openingBalance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOpeningBalance())
            )
            .satisfies(a ->
                assertThat(a.getBalance()).as("check balance").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBalance())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartyUpdatableRelationshipsEquals(Party expected, Party actual) {
        assertThat(actual)
            .as("Verify Party relationships")
            .satisfies(a -> assertThat(a.getBusiness()).as("check business").isEqualTo(expected.getBusiness()));
    }
}
