package com.finance.app.domain;

import static com.finance.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PaymentAllocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentAllocationAllPropertiesEquals(PaymentAllocation expected, PaymentAllocation actual) {
        assertPaymentAllocationAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentAllocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentAllocationAllUpdatablePropertiesEquals(PaymentAllocation expected, PaymentAllocation actual) {
        assertPaymentAllocationUpdatableFieldsEquals(expected, actual);
        assertPaymentAllocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentAllocationAutoGeneratedPropertiesEquals(PaymentAllocation expected, PaymentAllocation actual) {
        assertThat(actual)
            .as("Verify PaymentAllocation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentAllocationUpdatableFieldsEquals(PaymentAllocation expected, PaymentAllocation actual) {
        assertThat(actual)
            .as("Verify PaymentAllocation relevant properties")
            .satisfies(a -> assertThat(a.getDocId()).as("check docId").isEqualTo(expected.getDocId()))
            .satisfies(a -> assertThat(a.getDocNumber()).as("check docNumber").isEqualTo(expected.getDocNumber()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentAllocationUpdatableRelationshipsEquals(PaymentAllocation expected, PaymentAllocation actual) {
        assertThat(actual)
            .as("Verify PaymentAllocation relationships")
            .satisfies(a -> assertThat(a.getPayment()).as("check payment").isEqualTo(expected.getPayment()));
    }
}
