package com.finance.app.domain;

import static com.finance.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PurchaseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseAllPropertiesEquals(Purchase expected, Purchase actual) {
        assertPurchaseAutoGeneratedPropertiesEquals(expected, actual);
        assertPurchaseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseAllUpdatablePropertiesEquals(Purchase expected, Purchase actual) {
        assertPurchaseUpdatableFieldsEquals(expected, actual);
        assertPurchaseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseAutoGeneratedPropertiesEquals(Purchase expected, Purchase actual) {
        assertThat(actual)
            .as("Verify Purchase auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseUpdatableFieldsEquals(Purchase expected, Purchase actual) {
        assertThat(actual)
            .as("Verify Purchase relevant properties")
            .satisfies(a -> assertThat(a.getNumber()).as("check number").isEqualTo(expected.getNumber()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getDueDate()).as("check dueDate").isEqualTo(expected.getDueDate()))
            .satisfies(a -> assertThat(a.getPartyName()).as("check partyName").isEqualTo(expected.getPartyName()))
            .satisfies(a -> assertThat(a.getPartyState()).as("check partyState").isEqualTo(expected.getPartyState()))
            .satisfies(a -> assertThat(a.getBusinessState()).as("check businessState").isEqualTo(expected.getBusinessState()))
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a ->
                assertThat(a.getItemDiscountTotal())
                    .as("check itemDiscountTotal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getItemDiscountTotal())
            )
            .satisfies(a ->
                assertThat(a.getOverallDiscountKind()).as("check overallDiscountKind").isEqualTo(expected.getOverallDiscountKind())
            )
            .satisfies(a ->
                assertThat(a.getOverallDiscountValue())
                    .as("check overallDiscountValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOverallDiscountValue())
            )
            .satisfies(a ->
                assertThat(a.getOverallDiscountAmount())
                    .as("check overallDiscountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOverallDiscountAmount())
            )
            .satisfies(a ->
                assertThat(a.getTaxableValue())
                    .as("check taxableValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTaxableValue())
            )
            .satisfies(a -> assertThat(a.getCgst()).as("check cgst").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCgst()))
            .satisfies(a -> assertThat(a.getSgst()).as("check sgst").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSgst()))
            .satisfies(a -> assertThat(a.getIgst()).as("check igst").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getIgst()))
            .satisfies(a ->
                assertThat(a.getTaxTotal()).as("check taxTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxTotal())
            )
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()))
            .satisfies(a ->
                assertThat(a.getPaidAmount())
                    .as("check paidAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPaidAmount())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getKind()).as("check kind").isEqualTo(expected.getKind()))
            .satisfies(a -> assertThat(a.getSourcePurchaseId()).as("check sourcePurchaseId").isEqualTo(expected.getSourcePurchaseId()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getTerms()).as("check terms").isEqualTo(expected.getTerms()))
            .satisfies(a -> assertThat(a.getFinalizedAt()).as("check finalizedAt").isEqualTo(expected.getFinalizedAt()))
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseUpdatableRelationshipsEquals(Purchase expected, Purchase actual) {
        assertThat(actual)
            .as("Verify Purchase relationships")
            .satisfies(a -> assertThat(a.getBusiness()).as("check business").isEqualTo(expected.getBusiness()))
            .satisfies(a -> assertThat(a.getParty()).as("check party").isEqualTo(expected.getParty()));
    }
}
