package com.finance.app.domain;

import static com.finance.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PurchaseLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseLineAllPropertiesEquals(PurchaseLine expected, PurchaseLine actual) {
        assertPurchaseLineAutoGeneratedPropertiesEquals(expected, actual);
        assertPurchaseLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseLineAllUpdatablePropertiesEquals(PurchaseLine expected, PurchaseLine actual) {
        assertPurchaseLineUpdatableFieldsEquals(expected, actual);
        assertPurchaseLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseLineAutoGeneratedPropertiesEquals(PurchaseLine expected, PurchaseLine actual) {
        assertThat(actual)
            .as("Verify PurchaseLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseLineUpdatableFieldsEquals(PurchaseLine expected, PurchaseLine actual) {
        assertThat(actual)
            .as("Verify PurchaseLine relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getQty()).as("check qty").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQty()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getRate()).as("check rate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRate()))
            .satisfies(a -> assertThat(a.getDiscountKind()).as("check discountKind").isEqualTo(expected.getDiscountKind()))
            .satisfies(a ->
                assertThat(a.getDiscountValue())
                    .as("check discountValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountValue())
            )
            .satisfies(a ->
                assertThat(a.getTaxPercent())
                    .as("check taxPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTaxPercent())
            )
            .satisfies(a -> assertThat(a.getLineOrder()).as("check lineOrder").isEqualTo(expected.getLineOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseLineUpdatableRelationshipsEquals(PurchaseLine expected, PurchaseLine actual) {
        assertThat(actual)
            .as("Verify PurchaseLine relationships")
            .satisfies(a -> assertThat(a.getItem()).as("check item").isEqualTo(expected.getItem()))
            .satisfies(a -> assertThat(a.getPurchase()).as("check purchase").isEqualTo(expected.getPurchase()));
    }
}
