package com.finance.app.domain;

import static com.finance.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TransferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferAllPropertiesEquals(Transfer expected, Transfer actual) {
        assertTransferAutoGeneratedPropertiesEquals(expected, actual);
        assertTransferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferAllUpdatablePropertiesEquals(Transfer expected, Transfer actual) {
        assertTransferUpdatableFieldsEquals(expected, actual);
        assertTransferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferAutoGeneratedPropertiesEquals(Transfer expected, Transfer actual) {
        assertThat(actual)
            .as("Verify Transfer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferUpdatableFieldsEquals(Transfer expected, Transfer actual) {
        assertThat(actual)
            .as("Verify Transfer relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferUpdatableRelationshipsEquals(Transfer expected, Transfer actual) {
        assertThat(actual)
            .as("Verify Transfer relationships")
            .satisfies(a -> assertThat(a.getBusiness()).as("check business").isEqualTo(expected.getBusiness()))
            .satisfies(a -> assertThat(a.getFromAccount()).as("check fromAccount").isEqualTo(expected.getFromAccount()))
            .satisfies(a -> assertThat(a.getToAccount()).as("check toAccount").isEqualTo(expected.getToAccount()));
    }
}
