/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartiesNewRouteImport } from './routes/parties.new'
import { Route as PartiesIdRouteImport } from './routes/parties.$id'
import { Route as BusinessesNewRouteImport } from './routes/businesses.new'
import { Route as PartiesIdEditRouteImport } from './routes/parties.$id.edit'
import { Route as BusinessesIdEditRouteImport } from './routes/businesses.$id.edit'

const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesNewRoute = PartiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PartiesRoute,
} as any)
const PartiesIdRoute = PartiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartiesRoute,
} as any)
const BusinessesNewRoute = BusinessesNewRouteImport.update({
  id: '/businesses/new',
  path: '/businesses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdEditRoute = PartiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PartiesIdRoute,
} as any)
const BusinessesIdEditRoute = BusinessesIdEditRouteImport.update({
  id: '/businesses/$id/edit',
  path: '/businesses/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/parties': typeof PartiesRouteWithChildren
  '/businesses/new': typeof BusinessesNewRoute
  '/parties/$id': typeof PartiesIdRouteWithChildren
  '/parties/new': typeof PartiesNewRoute
  '/businesses/$id/edit': typeof BusinessesIdEditRoute
  '/parties/$id/edit': typeof PartiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/parties': typeof PartiesRouteWithChildren
  '/businesses/new': typeof BusinessesNewRoute
  '/parties/$id': typeof PartiesIdRouteWithChildren
  '/parties/new': typeof PartiesNewRoute
  '/businesses/$id/edit': typeof BusinessesIdEditRoute
  '/parties/$id/edit': typeof PartiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/parties': typeof PartiesRouteWithChildren
  '/businesses/new': typeof BusinessesNewRoute
  '/parties/$id': typeof PartiesIdRouteWithChildren
  '/parties/new': typeof PartiesNewRoute
  '/businesses/$id/edit': typeof BusinessesIdEditRoute
  '/parties/$id/edit': typeof PartiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/items'
    | '/parties'
    | '/businesses/new'
    | '/parties/$id'
    | '/parties/new'
    | '/businesses/$id/edit'
    | '/parties/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/items'
    | '/parties'
    | '/businesses/new'
    | '/parties/$id'
    | '/parties/new'
    | '/businesses/$id/edit'
    | '/parties/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/items'
    | '/parties'
    | '/businesses/new'
    | '/parties/$id'
    | '/parties/new'
    | '/businesses/$id/edit'
    | '/parties/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRoute: typeof ItemsRoute
  PartiesRoute: typeof PartiesRouteWithChildren
  BusinessesNewRoute: typeof BusinessesNewRoute
  BusinessesIdEditRoute: typeof BusinessesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/new': {
      id: '/parties/new'
      path: '/new'
      fullPath: '/parties/new'
      preLoaderRoute: typeof PartiesNewRouteImport
      parentRoute: typeof PartiesRoute
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteImport
      parentRoute: typeof PartiesRoute
    }
    '/businesses/new': {
      id: '/businesses/new'
      path: '/businesses/new'
      fullPath: '/businesses/new'
      preLoaderRoute: typeof BusinessesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id/edit': {
      id: '/parties/$id/edit'
      path: '/edit'
      fullPath: '/parties/$id/edit'
      preLoaderRoute: typeof PartiesIdEditRouteImport
      parentRoute: typeof PartiesIdRoute
    }
    '/businesses/$id/edit': {
      id: '/businesses/$id/edit'
      path: '/businesses/$id/edit'
      fullPath: '/businesses/$id/edit'
      preLoaderRoute: typeof BusinessesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartiesIdRouteChildren {
  PartiesIdEditRoute: typeof PartiesIdEditRoute
}

const PartiesIdRouteChildren: PartiesIdRouteChildren = {
  PartiesIdEditRoute: PartiesIdEditRoute,
}

const PartiesIdRouteWithChildren = PartiesIdRoute._addFileChildren(
  PartiesIdRouteChildren,
)

interface PartiesRouteChildren {
  PartiesIdRoute: typeof PartiesIdRouteWithChildren
  PartiesNewRoute: typeof PartiesNewRoute
}

const PartiesRouteChildren: PartiesRouteChildren = {
  PartiesIdRoute: PartiesIdRouteWithChildren,
  PartiesNewRoute: PartiesNewRoute,
}

const PartiesRouteWithChildren =
  PartiesRoute._addFileChildren(PartiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRoute: ItemsRoute,
  PartiesRoute: PartiesRouteWithChildren,
  BusinessesNewRoute: BusinessesNewRoute,
  BusinessesIdEditRoute: BusinessesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
