/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurchasesNewRouteImport } from './routes/purchases.new'
import { Route as PurchasesIdRouteImport } from './routes/purchases.$id'
import { Route as PaymentsNewRouteImport } from './routes/payments.new'
import { Route as PartiesNewRouteImport } from './routes/parties.new'
import { Route as PartiesIdRouteImport } from './routes/parties.$id'
import { Route as ItemsNewRouteImport } from './routes/items.new'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as ExpensesNewRouteImport } from './routes/expenses.new'
import { Route as CategoriesExpenseRouteImport } from './routes/categories.expense'
import { Route as BusinessesNewRouteImport } from './routes/businesses.new'
import { Route as AccountsTransferRouteImport } from './routes/accounts.transfer'
import { Route as AccountsNewRouteImport } from './routes/accounts.new'
import { Route as ExpensesIdIndexRouteImport } from './routes/expenses.$id.index'
import { Route as AccountsIdIndexRouteImport } from './routes/accounts.$id.index'
import { Route as PurchasesIdPrintRouteImport } from './routes/purchases.$id.print'
import { Route as PurchasesIdEditRouteImport } from './routes/purchases.$id.edit'
import { Route as PartiesIdEditRouteImport } from './routes/parties.$id.edit'
import { Route as ItemsIdEditRouteImport } from './routes/items.$id.edit'
import { Route as InvoicesIdPrintRouteImport } from './routes/invoices.$id.print'
import { Route as InvoicesIdEditRouteImport } from './routes/invoices.$id.edit'
import { Route as ExpensesIdEditRouteImport } from './routes/expenses.$id.edit'
import { Route as BusinessesIdEditRouteImport } from './routes/businesses.$id.edit'
import { Route as AccountsIdEditRouteImport } from './routes/accounts.$id.edit'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasesRoute,
} as any)
const PurchasesIdRoute = PurchasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchasesRoute,
} as any)
const PaymentsNewRoute = PaymentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PaymentsRoute,
} as any)
const PartiesNewRoute = PartiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PartiesRoute,
} as any)
const PartiesIdRoute = PartiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartiesRoute,
} as any)
const ItemsNewRoute = ItemsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItemsRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ExpensesRoute,
} as any)
const CategoriesExpenseRoute = CategoriesExpenseRouteImport.update({
  id: '/categories/expense',
  path: '/categories/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesNewRoute = BusinessesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BusinessesRoute,
} as any)
const AccountsTransferRoute = AccountsTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccountsRoute,
} as any)
const ExpensesIdIndexRoute = ExpensesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => ExpensesRoute,
} as any)
const AccountsIdIndexRoute = AccountsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AccountsRoute,
} as any)
const PurchasesIdPrintRoute = PurchasesIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => PurchasesIdRoute,
} as any)
const PurchasesIdEditRoute = PurchasesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PurchasesIdRoute,
} as any)
const PartiesIdEditRoute = PartiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PartiesIdRoute,
} as any)
const ItemsIdEditRoute = ItemsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ItemsIdRoute,
} as any)
const InvoicesIdPrintRoute = InvoicesIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => InvoicesIdRoute,
} as any)
const InvoicesIdEditRoute = InvoicesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InvoicesIdRoute,
} as any)
const ExpensesIdEditRoute = ExpensesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => ExpensesRoute,
} as any)
const BusinessesIdEditRoute = BusinessesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => BusinessesRoute,
} as any)
const AccountsIdEditRoute = AccountsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/businesses': typeof BusinessesRouteWithChildren
  '/expenses': typeof ExpensesRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/parties': typeof PartiesRouteWithChildren
  '/payments': typeof PaymentsRouteWithChildren
  '/purchases': typeof PurchasesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/accounts/transfer': typeof AccountsTransferRoute
  '/businesses/new': typeof BusinessesNewRoute
  '/categories/expense': typeof CategoriesExpenseRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/items/new': typeof ItemsNewRoute
  '/parties/$id': typeof PartiesIdRouteWithChildren
  '/parties/new': typeof PartiesNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/purchases/$id': typeof PurchasesIdRouteWithChildren
  '/purchases/new': typeof PurchasesNewRoute
  '/accounts/$id/edit': typeof AccountsIdEditRoute
  '/businesses/$id/edit': typeof BusinessesIdEditRoute
  '/expenses/$id/edit': typeof ExpensesIdEditRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/invoices/$id/print': typeof InvoicesIdPrintRoute
  '/items/$id/edit': typeof ItemsIdEditRoute
  '/parties/$id/edit': typeof PartiesIdEditRoute
  '/purchases/$id/edit': typeof PurchasesIdEditRoute
  '/purchases/$id/print': typeof PurchasesIdPrintRoute
  '/accounts/$id/': typeof AccountsIdIndexRoute
  '/expenses/$id/': typeof ExpensesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/businesses': typeof BusinessesRouteWithChildren
  '/expenses': typeof ExpensesRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/parties': typeof PartiesRouteWithChildren
  '/payments': typeof PaymentsRouteWithChildren
  '/purchases': typeof PurchasesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/accounts/transfer': typeof AccountsTransferRoute
  '/businesses/new': typeof BusinessesNewRoute
  '/categories/expense': typeof CategoriesExpenseRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/items/new': typeof ItemsNewRoute
  '/parties/$id': typeof PartiesIdRouteWithChildren
  '/parties/new': typeof PartiesNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/purchases/$id': typeof PurchasesIdRouteWithChildren
  '/purchases/new': typeof PurchasesNewRoute
  '/accounts/$id/edit': typeof AccountsIdEditRoute
  '/businesses/$id/edit': typeof BusinessesIdEditRoute
  '/expenses/$id/edit': typeof ExpensesIdEditRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/invoices/$id/print': typeof InvoicesIdPrintRoute
  '/items/$id/edit': typeof ItemsIdEditRoute
  '/parties/$id/edit': typeof PartiesIdEditRoute
  '/purchases/$id/edit': typeof PurchasesIdEditRoute
  '/purchases/$id/print': typeof PurchasesIdPrintRoute
  '/accounts/$id': typeof AccountsIdIndexRoute
  '/expenses/$id': typeof ExpensesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/businesses': typeof BusinessesRouteWithChildren
  '/expenses': typeof ExpensesRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/parties': typeof PartiesRouteWithChildren
  '/payments': typeof PaymentsRouteWithChildren
  '/purchases': typeof PurchasesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/accounts/transfer': typeof AccountsTransferRoute
  '/businesses/new': typeof BusinessesNewRoute
  '/categories/expense': typeof CategoriesExpenseRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/items/new': typeof ItemsNewRoute
  '/parties/$id': typeof PartiesIdRouteWithChildren
  '/parties/new': typeof PartiesNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/purchases/$id': typeof PurchasesIdRouteWithChildren
  '/purchases/new': typeof PurchasesNewRoute
  '/accounts/$id/edit': typeof AccountsIdEditRoute
  '/businesses/$id/edit': typeof BusinessesIdEditRoute
  '/expenses/$id/edit': typeof ExpensesIdEditRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/invoices/$id/print': typeof InvoicesIdPrintRoute
  '/items/$id/edit': typeof ItemsIdEditRoute
  '/parties/$id/edit': typeof PartiesIdEditRoute
  '/purchases/$id/edit': typeof PurchasesIdEditRoute
  '/purchases/$id/print': typeof PurchasesIdPrintRoute
  '/accounts/$id/': typeof AccountsIdIndexRoute
  '/expenses/$id/': typeof ExpensesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/businesses'
    | '/expenses'
    | '/invoices'
    | '/items'
    | '/parties'
    | '/payments'
    | '/purchases'
    | '/reports'
    | '/accounts/new'
    | '/accounts/transfer'
    | '/businesses/new'
    | '/categories/expense'
    | '/expenses/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/items/$id'
    | '/items/new'
    | '/parties/$id'
    | '/parties/new'
    | '/payments/new'
    | '/purchases/$id'
    | '/purchases/new'
    | '/accounts/$id/edit'
    | '/businesses/$id/edit'
    | '/expenses/$id/edit'
    | '/invoices/$id/edit'
    | '/invoices/$id/print'
    | '/items/$id/edit'
    | '/parties/$id/edit'
    | '/purchases/$id/edit'
    | '/purchases/$id/print'
    | '/accounts/$id/'
    | '/expenses/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/businesses'
    | '/expenses'
    | '/invoices'
    | '/items'
    | '/parties'
    | '/payments'
    | '/purchases'
    | '/reports'
    | '/accounts/new'
    | '/accounts/transfer'
    | '/businesses/new'
    | '/categories/expense'
    | '/expenses/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/items/$id'
    | '/items/new'
    | '/parties/$id'
    | '/parties/new'
    | '/payments/new'
    | '/purchases/$id'
    | '/purchases/new'
    | '/accounts/$id/edit'
    | '/businesses/$id/edit'
    | '/expenses/$id/edit'
    | '/invoices/$id/edit'
    | '/invoices/$id/print'
    | '/items/$id/edit'
    | '/parties/$id/edit'
    | '/purchases/$id/edit'
    | '/purchases/$id/print'
    | '/accounts/$id'
    | '/expenses/$id'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/businesses'
    | '/expenses'
    | '/invoices'
    | '/items'
    | '/parties'
    | '/payments'
    | '/purchases'
    | '/reports'
    | '/accounts/new'
    | '/accounts/transfer'
    | '/businesses/new'
    | '/categories/expense'
    | '/expenses/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/items/$id'
    | '/items/new'
    | '/parties/$id'
    | '/parties/new'
    | '/payments/new'
    | '/purchases/$id'
    | '/purchases/new'
    | '/accounts/$id/edit'
    | '/businesses/$id/edit'
    | '/expenses/$id/edit'
    | '/invoices/$id/edit'
    | '/invoices/$id/print'
    | '/items/$id/edit'
    | '/parties/$id/edit'
    | '/purchases/$id/edit'
    | '/purchases/$id/print'
    | '/accounts/$id/'
    | '/expenses/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  BusinessesRoute: typeof BusinessesRouteWithChildren
  ExpensesRoute: typeof ExpensesRouteWithChildren
  InvoicesRoute: typeof InvoicesRouteWithChildren
  ItemsRoute: typeof ItemsRouteWithChildren
  PartiesRoute: typeof PartiesRouteWithChildren
  PaymentsRoute: typeof PaymentsRouteWithChildren
  PurchasesRoute: typeof PurchasesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  CategoriesExpenseRoute: typeof CategoriesExpenseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof PurchasesRoute
    }
    '/purchases/$id': {
      id: '/purchases/$id'
      path: '/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof PurchasesIdRouteImport
      parentRoute: typeof PurchasesRoute
    }
    '/payments/new': {
      id: '/payments/new'
      path: '/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof PaymentsNewRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/parties/new': {
      id: '/parties/new'
      path: '/new'
      fullPath: '/parties/new'
      preLoaderRoute: typeof PartiesNewRouteImport
      parentRoute: typeof PartiesRoute
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteImport
      parentRoute: typeof PartiesRoute
    }
    '/items/new': {
      id: '/items/new'
      path: '/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof ItemsNewRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/categories/expense': {
      id: '/categories/expense'
      path: '/categories/expense'
      fullPath: '/categories/expense'
      preLoaderRoute: typeof CategoriesExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/new': {
      id: '/businesses/new'
      path: '/new'
      fullPath: '/businesses/new'
      preLoaderRoute: typeof BusinessesNewRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/accounts/transfer': {
      id: '/accounts/transfer'
      path: '/transfer'
      fullPath: '/accounts/transfer'
      preLoaderRoute: typeof AccountsTransferRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/expenses/$id/': {
      id: '/expenses/$id/'
      path: '/$id'
      fullPath: '/expenses/$id/'
      preLoaderRoute: typeof ExpensesIdIndexRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/accounts/$id/': {
      id: '/accounts/$id/'
      path: '/$id'
      fullPath: '/accounts/$id/'
      preLoaderRoute: typeof AccountsIdIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/purchases/$id/print': {
      id: '/purchases/$id/print'
      path: '/print'
      fullPath: '/purchases/$id/print'
      preLoaderRoute: typeof PurchasesIdPrintRouteImport
      parentRoute: typeof PurchasesIdRoute
    }
    '/purchases/$id/edit': {
      id: '/purchases/$id/edit'
      path: '/edit'
      fullPath: '/purchases/$id/edit'
      preLoaderRoute: typeof PurchasesIdEditRouteImport
      parentRoute: typeof PurchasesIdRoute
    }
    '/parties/$id/edit': {
      id: '/parties/$id/edit'
      path: '/edit'
      fullPath: '/parties/$id/edit'
      preLoaderRoute: typeof PartiesIdEditRouteImport
      parentRoute: typeof PartiesIdRoute
    }
    '/items/$id/edit': {
      id: '/items/$id/edit'
      path: '/edit'
      fullPath: '/items/$id/edit'
      preLoaderRoute: typeof ItemsIdEditRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/invoices/$id/print': {
      id: '/invoices/$id/print'
      path: '/print'
      fullPath: '/invoices/$id/print'
      preLoaderRoute: typeof InvoicesIdPrintRouteImport
      parentRoute: typeof InvoicesIdRoute
    }
    '/invoices/$id/edit': {
      id: '/invoices/$id/edit'
      path: '/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof InvoicesIdEditRouteImport
      parentRoute: typeof InvoicesIdRoute
    }
    '/expenses/$id/edit': {
      id: '/expenses/$id/edit'
      path: '/$id/edit'
      fullPath: '/expenses/$id/edit'
      preLoaderRoute: typeof ExpensesIdEditRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/businesses/$id/edit': {
      id: '/businesses/$id/edit'
      path: '/$id/edit'
      fullPath: '/businesses/$id/edit'
      preLoaderRoute: typeof BusinessesIdEditRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/accounts/$id/edit': {
      id: '/accounts/$id/edit'
      path: '/$id/edit'
      fullPath: '/accounts/$id/edit'
      preLoaderRoute: typeof AccountsIdEditRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsNewRoute: typeof AccountsNewRoute
  AccountsTransferRoute: typeof AccountsTransferRoute
  AccountsIdEditRoute: typeof AccountsIdEditRoute
  AccountsIdIndexRoute: typeof AccountsIdIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsNewRoute: AccountsNewRoute,
  AccountsTransferRoute: AccountsTransferRoute,
  AccountsIdEditRoute: AccountsIdEditRoute,
  AccountsIdIndexRoute: AccountsIdIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface BusinessesRouteChildren {
  BusinessesNewRoute: typeof BusinessesNewRoute
  BusinessesIdEditRoute: typeof BusinessesIdEditRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesNewRoute: BusinessesNewRoute,
  BusinessesIdEditRoute: BusinessesIdEditRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

interface ExpensesRouteChildren {
  ExpensesNewRoute: typeof ExpensesNewRoute
  ExpensesIdEditRoute: typeof ExpensesIdEditRoute
  ExpensesIdIndexRoute: typeof ExpensesIdIndexRoute
}

const ExpensesRouteChildren: ExpensesRouteChildren = {
  ExpensesNewRoute: ExpensesNewRoute,
  ExpensesIdEditRoute: ExpensesIdEditRoute,
  ExpensesIdIndexRoute: ExpensesIdIndexRoute,
}

const ExpensesRouteWithChildren = ExpensesRoute._addFileChildren(
  ExpensesRouteChildren,
)

interface InvoicesIdRouteChildren {
  InvoicesIdEditRoute: typeof InvoicesIdEditRoute
  InvoicesIdPrintRoute: typeof InvoicesIdPrintRoute
}

const InvoicesIdRouteChildren: InvoicesIdRouteChildren = {
  InvoicesIdEditRoute: InvoicesIdEditRoute,
  InvoicesIdPrintRoute: InvoicesIdPrintRoute,
}

const InvoicesIdRouteWithChildren = InvoicesIdRoute._addFileChildren(
  InvoicesIdRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRouteWithChildren
  InvoicesNewRoute: typeof InvoicesNewRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRouteWithChildren,
  InvoicesNewRoute: InvoicesNewRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface ItemsIdRouteChildren {
  ItemsIdEditRoute: typeof ItemsIdEditRoute
}

const ItemsIdRouteChildren: ItemsIdRouteChildren = {
  ItemsIdEditRoute: ItemsIdEditRoute,
}

const ItemsIdRouteWithChildren =
  ItemsIdRoute._addFileChildren(ItemsIdRouteChildren)

interface ItemsRouteChildren {
  ItemsIdRoute: typeof ItemsIdRouteWithChildren
  ItemsNewRoute: typeof ItemsNewRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsIdRoute: ItemsIdRouteWithChildren,
  ItemsNewRoute: ItemsNewRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

interface PartiesIdRouteChildren {
  PartiesIdEditRoute: typeof PartiesIdEditRoute
}

const PartiesIdRouteChildren: PartiesIdRouteChildren = {
  PartiesIdEditRoute: PartiesIdEditRoute,
}

const PartiesIdRouteWithChildren = PartiesIdRoute._addFileChildren(
  PartiesIdRouteChildren,
)

interface PartiesRouteChildren {
  PartiesIdRoute: typeof PartiesIdRouteWithChildren
  PartiesNewRoute: typeof PartiesNewRoute
}

const PartiesRouteChildren: PartiesRouteChildren = {
  PartiesIdRoute: PartiesIdRouteWithChildren,
  PartiesNewRoute: PartiesNewRoute,
}

const PartiesRouteWithChildren =
  PartiesRoute._addFileChildren(PartiesRouteChildren)

interface PaymentsRouteChildren {
  PaymentsNewRoute: typeof PaymentsNewRoute
}

const PaymentsRouteChildren: PaymentsRouteChildren = {
  PaymentsNewRoute: PaymentsNewRoute,
}

const PaymentsRouteWithChildren = PaymentsRoute._addFileChildren(
  PaymentsRouteChildren,
)

interface PurchasesIdRouteChildren {
  PurchasesIdEditRoute: typeof PurchasesIdEditRoute
  PurchasesIdPrintRoute: typeof PurchasesIdPrintRoute
}

const PurchasesIdRouteChildren: PurchasesIdRouteChildren = {
  PurchasesIdEditRoute: PurchasesIdEditRoute,
  PurchasesIdPrintRoute: PurchasesIdPrintRoute,
}

const PurchasesIdRouteWithChildren = PurchasesIdRoute._addFileChildren(
  PurchasesIdRouteChildren,
)

interface PurchasesRouteChildren {
  PurchasesIdRoute: typeof PurchasesIdRouteWithChildren
  PurchasesNewRoute: typeof PurchasesNewRoute
}

const PurchasesRouteChildren: PurchasesRouteChildren = {
  PurchasesIdRoute: PurchasesIdRouteWithChildren,
  PurchasesNewRoute: PurchasesNewRoute,
}

const PurchasesRouteWithChildren = PurchasesRoute._addFileChildren(
  PurchasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  BusinessesRoute: BusinessesRouteWithChildren,
  ExpensesRoute: ExpensesRouteWithChildren,
  InvoicesRoute: InvoicesRouteWithChildren,
  ItemsRoute: ItemsRouteWithChildren,
  PartiesRoute: PartiesRouteWithChildren,
  PaymentsRoute: PaymentsRouteWithChildren,
  PurchasesRoute: PurchasesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  CategoriesExpenseRoute: CategoriesExpenseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
